DFMS/FirmWebApp/Controllers/Cow/FeedEntryController.cs
using Firm.Service.Services.Cow_Services;
using Firm.Service.Services.Doctor_Services;
using Firm.Service.Services.FeedCategory_Services;
using Firm.Service.Services.FeedEntry_Services;
using Firm.Service.Services.Vaccine_Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FirmWebApp.Controllers.Cow
{
    public class FeedEntryController : Controller
    {
        public readonly IFeedCategoryService feedCategoryService;
        public readonly IFeedEntryService feedEntryService;
        public FeedEntryController(IFeedCategoryService feedCategoryService , IFeedEntryService feedEntryService)
        {
            this.feedCategoryService = feedCategoryService;
            this.feedEntryService = feedEntryService;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.feedCategoryList = new SelectList((await feedCategoryService.GetAll()).Select(s => new { Id = s.Id, Name = s.FeedCategoryName }), "Id", "Name");
            var data = await feedEntryService.GetAll();
            return View(data);
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.feedCategoryList = new SelectList((await feedCategoryService.GetAll()).Select(s => new { Id = s.Id, Name = s.FeedCategoryName }), "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(FeedEntryServiceVM model)
        {
            try
            {
                var result = await feedEntryService.AddNewFeedEntry(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while adding Feed Entry.");
                return View(model);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            ViewBag.feedCategoryList = new SelectList((await feedCategoryService.GetAll()).Select(s => new { Id = s.Id, Name = s.FeedCategoryName }), "Id", "Name");
            var obj = await feedEntryService.GetById(id);
            return View(obj);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(FeedEntryServiceVM model)
        {
            try
            {
                var result = await feedEntryService.UpdateFeedEntry(model);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while adding Feed Entry.");
                return View(model);
            }
        }


        public async Task<IActionResult> Delete(long id)
        {
            var obj = await feedEntryService.Remove(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> GetUnitName(int categoryId)
        {
            var feedCategory = await feedCategoryService.GetById(categoryId);
            if (feedCategory != null)
            {
                return Json(new { unitName = feedCategory.UnitName });
            }

            return Json(new { unitName = "" }); // Return an empty unitName if no category is found
        }
    }
}

DFMS/FirmWebApp/Views/FeedEntry/Create.cshtml
@model FeedEntryServiceVM
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}
<div class="content-header">
    <div class="container-fluid ">
        <div class="breadcrumb d-flex justify-content-between align-items-center shadow pl-3 pr-3">
            <ol class="breadcrumb mb-0 p-0">
                <li class="breadcrumb-item"><a href="/Admin/Index">Home</a></li>
                <li class="breadcrumb-item active">Feed Entry</li>
            </ol>
            <div>
                <a asp-action="Index"><i class="fa fa-arrow-left mr-2"></i>Back To List</a>
            </div>
        </div>
    </div>
</div>
<section class="content">
    <div class="container-fluid">
        <div class="">
            <div class="card-header">
                <h5 class="card-title">Feed Entry</h5>
            </div>

            <div class="card-body">
                <form asp-action="Create" asp-controller="FeedEntry" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    @if (!string.IsNullOrEmpty(ViewData["ErrorMessage"] as string))
                    {
                        <div class="alert alert-warning">
                            @ViewData["ErrorMessage"]
                        </div>
                    }
                    <div class="row mx-2">
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="Date" class="control-label"> Date</label>
                                <input asp-for="Date" type="date" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="FeedCategoryId" class="control-label">Feed Category</label>
                                <select asp-for="FeedCategoryId" class="form-control" asp-items="ViewBag.feedCategoryList">
                                    <option value="">-- Select Feed Category--</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="Quantity" class="control-label">Total Quantity</label>
                                <input asp-for="Quantity" class="form-control" placeholder="Feed amount">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="UnitPrice" class="control-label">Unit Price</label>
                                <input asp-for="UnitPrice" class="form-control" placeholder="Per unit price">
                            </div>
                        </div>
                    </div>
                    <div class="row mx-2">
                        <div class="form-group col-sm-12">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>


                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            $('#Feed').addClass('menu-open');
            $('#FeedEntry').addClass('active');

        });
    </script>
    <script>
        window.setTimeout(function () {
            $(".alert").fadeTo(500,).slideUp(500, function () {
                $(this).remove();
            });
        }, 4000);
    </script>
    <script>
        $(document).ready(function () {
            $('#FeedCategoryId').change(function () { // Listen for change event on the select element
                var categoryId = $(this).val(); // Get the selected categoryId

                $.ajax({
                    url: '/FeedEntry/GetUnitName', // Replace YourController with the appropriate controller name
                    type: 'GET',
                    data: { categoryId: categoryId }, // Pass the selected categoryId as a parameter
                    success: function (data) {
                        var unitName = data.unitName; // Retrieve the unitName from the response

                        $('#Quantity').attr('placeholder', 'Feed amount in ' + unitName);
                        $('#UnitPrice').attr('placeholder', 'Per ' + unitName + ' price');
                    }
                });
            });
        });

    </script>
  }

DFMS/FirmWebApp/Views/FeedEntry/Edit.cshtml
@model FeedEntryServiceVM
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<div class="content-header">
    <div class="container-fluid ">
        <div class="breadcrumb d-flex justify-content-between align-items-center shadow pl-3 pr-3">
            <ol class="breadcrumb mb-0 p-0">
                <li class="breadcrumb-item"><a href="/Admin/Index">Home</a></li>
                <li class="breadcrumb-item active">Feed Entry</li>
            </ol>
            <div>
                <a asp-action="Index"><i class="fa fa-arrow-left mr-2"></i>Back To List</a>
            </div>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <div class="">
            <div class="card-header">
                <h5 class="card-title">Feed Entry</h5>
            </div>

            <div class="card-body">
                <form asp-action="Edit" asp-controller="FeedEntry" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    @if (!string.IsNullOrEmpty(ViewData["ErrorMessage"] as string))
                    {
                        <div class="alert alert-warning">
                            @ViewData["ErrorMessage"]
                        </div>
                    }
                    <div class="row mx-2">
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="Date" class="control-label"> Date</label>
                                <input asp-for="Date" type="date" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="FeedCategoryId" class="control-label">Feed Category</label>
                                <select asp-for="FeedCategoryId" class="form-control" asp-items="ViewBag.feedCategoryList">
                                    <option value="">-- Select Feed Category--</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="Quantity" class="control-label">Total Quantity</label>
                                <input asp-for="Quantity" class="form-control" placeholder="Feed amount">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="UnitPrice" class="control-label">Unit Price</label>
                                <input asp-for="UnitPrice" class="form-control" placeholder="Per unit price">
                            </div>
                        </div>
                    </div>
                    <div class="row mx-2">
                        <div class="form-group col-sm-12">
                            <button type="submit" class="btn btn-warning">Update</button>
                        </div>
                    </div>

                    <!-- Add a hidden input field for the Id -->
                    <input type="hidden" asp-for="Id" />

                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            $('#Feed').addClass('menu-open');
            $('#FeedEntry').addClass('active');

        });
    </script>
    <script>
        window.setTimeout(function () {
            $(".alert").fadeTo(500,).slideUp(500, function () {
                $(this).remove();
            });
        }, 4000);
    </script>
    <script>
        $(document).ready(function () {
            $('#FeedCategoryId').change(function () { // Listen for change event on the select element
                var categoryId = $(this).val(); // Get the selected categoryId

                $.ajax({
                    url: '/FeedEntry/GetUnitName', // Replace YourController with the appropriate controller name
                    type: 'GET',
                    data: { categoryId: categoryId }, // Pass the selected categoryId as a parameter
                    success: function (data) {
                        var unitName = data.unitName; // Retrieve the unitName from the response

                        $('#Quantity').attr('placeholder', 'Feed amount in ' + unitName);
                        $('#UnitPrice').attr('placeholder', 'Per ' + unitName + ' price');
                    }
                });
            });
        });

    </script>
  }

DFMS/FirmWebApp/Views/FeedEntry/Index.cshtml
@model List<FeedEntryServiceVM>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
    int SN = 1;
}
<div class="content-header">
    <div class="container-fluid ">
        <div class="breadcrumb d-flex justify-content-between align-items-center shadow pl-3 pr-3">
            <ol class="breadcrumb mb-0 p-0">
                <li class="breadcrumb-item"><a href="/Admin/Index">Home</a></li>
                <li class="breadcrumb-item active">Feed Entry</li>
            </ol>
            <div>
                <a asp-action="Create"><i class="fa fa-plus"></i>Feed : New Entry</a>
            </div>
        </div>
    </div>
</div>
<section class="content">

    <div class="card-header">
        <h5 class="card-title">Feed Entries</h5>
    </div>
    <div class="card-body">
        <div class="table-responsive-sm">
            <table id="feedEntriestable" class="table  table-bordered table-hover">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Date</th>
                        <th>Feed Category</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int index = 0;
                    }

                    @foreach (var entry in Model)
                    {
                        <tr>
                            <td>@SN</td>
                            <td>@entry.Date.ToShortDateString()</td>
                            <td>@entry.FeedCategoryName</td>
                            <td>@entry.Quantity</td>
                            <td>@entry.UnitPrice</td>
                           
                                <td>
                                <a href="@Url.Action("Edit", new { id = entry.Id })">Edit</a>
                                   <span> | </span>
                                <a href="@Url.Action("Delete", new { id = entry.Id })" onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
                                </td>
                        </tr>
                        index++;
                        SN++;
                    }
                </tbody>
            </table>
        </div>


    </div>
</section>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            $('#Feed').addClass('menu-open');
            $('#FeedEntry').addClass('active');

            $('#feedEntriestable').DataTable({
                // Configure DataTable options
                "paging": true,
                "ordering": true,
                "info": true,
                order: [[0, 'desc']],
            });

        });
    </script>
  }