DFMS/FirmWebApp/Controllers/Cow/CowBreedController.cs
using Firm.Service.Services.Breed_Service;
using Firm.Service.Services.Cow_Services;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace FirmWebApp.Controllers.Cow
{
    public class CowBreedController : Controller
    {
        public readonly IBreedService breedService;
        public CowBreedController(IBreedService breedService)
        {
            this.breedService = breedService;
        }
        public async Task<IActionResult> Index()
        {
            var list = await breedService.GetAll();
            return View(list);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(BreedServiceViewModel model)
        {
            try
            {
                var result = await breedService.AddBreed(model);

                if (!string.IsNullOrEmpty(result.ErrorMessage))
                {
                    ViewData["ErrorMessage"] = result.ErrorMessage;
                    return View(model);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while adding breed.");
                return View(model);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            var obj = await breedService.GetById(id);
            return View(obj);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(BreedServiceViewModel model)
        {
            try
            {
                var result = await breedService.UpdateBreed(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while updating breed.");
                return View(model);
            }
        }


        public async Task<IActionResult> Delete(long id)
        {
            var obj = await breedService.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

DFMS/FirmWebApp/Controllers/Cow/CowController.cs
using Firm.Service.Services.Breed_Service;
using Firm.Service.Services.Cow_Services;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace FirmWebApp.Controllers.Cow
{
    public class CowController : Controller
    {
        public readonly ICowService cowService;
        public readonly IBreedService breedService;
        public CowController(ICowService cowService, IBreedService breedService)
        {
            this.cowService = cowService;
            this.breedService = breedService;
        }
        public async Task<IActionResult> Index()
        {
            var list = await breedService.GetAll();
            ViewBag.breedlist = new SelectList((list).Select(s => new { Id = s.BreedId, Name = s.BreedName }), "Id", "Name");
            var data = await cowService.GetAll();
            return View(data);
        }
        public async Task<IActionResult> Create()
        {
            var list = await breedService.GetAll();
            ViewBag.breedlist = new SelectList((list).Select(s => new { Id = s.BreedId, Name = s.BreedName }), "Id", "Name");
           
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CowServiceViewModel model)
        {
            try
            {
                var result = await cowService.AddNewCow(model);

                if (!string.IsNullOrEmpty(result.ErrorMessage))
                {
                    ViewData["ErrorMessage"] = result.ErrorMessage;
                    return View(model);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while adding cow.");
                return View(model);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            var list = await breedService.GetAll();
            ViewBag.breedlist = new SelectList((list).Select(s => new { Id = s.BreedId, Name = s.BreedName }), "Id", "Name");

            var obj = await cowService.GetById(id);
            return View(obj);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CowServiceViewModel model)
        {
            try
            {
                var result = await cowService.UpdateCow(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while adding cow.");
                return View(model);
            }
        }
        public async Task<IActionResult> Delete(long id)
        {
            var obj = await cowService.Remove(id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> CowSummary(long id)
        {
            var obj = await cowService.GetCowHistoryById(id);
            return PartialView("_CowSummary", obj);
        }


    }
}

DFMS/FirmWebApp/Controllers/Cow/DoctorController.cs
using Firm.Service.Services.Doctor_Services;
using Microsoft.AspNetCore.Mvc;

namespace FirmWebApp.Controllers.Cow
{
    public class DoctorController : Controller
    {
        public readonly IDoctorService doctorService;
        public DoctorController(IDoctorService doctorService)
        {
            this.doctorService = doctorService;
        }
        public async Task<IActionResult> Index()
        {
            var list = await doctorService.GetAll();
            return View(list);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(DoctorServiceViewModel model)
        {
            try
            {
                var result = await doctorService.AddNewDoctor(model);

                if (!string.IsNullOrEmpty(result.ErrorMessage))
                {
                    ViewData["ErrorMessage"] = result.ErrorMessage;
                    return View(model);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while adding doctor.");
                return View(model);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            var obj = await doctorService.GetById(id);
            return View(obj);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(DoctorServiceViewModel model)
        {
            try
            {
                var result = await doctorService.UpdateDoctor(model);

                if (!string.IsNullOrEmpty(result.ErrorMessage))
                {
                    ViewData["ErrorMessage"] = result.ErrorMessage;
                    return View(model);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while updating doctor.");
                return View(model);
            }
        }


        public async Task<IActionResult> Delete(long id)
        {
            var obj = await doctorService.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

DFMS/FirmWebApp/Controllers/Cow/ExpenseApprovalController.cs
using Firm.Service.Services.ExpenseApproval_Services;
using Firm.Service.Services.Vaccine_Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FirmWebApp.Controllers.Cow
{
    public class ExpenseApprovalController : Controller
    {
        public readonly IExpenseApprovalService expenseApprovalService;
        public ExpenseApprovalController(IExpenseApprovalService expenseApprovalService)
        {
            this.expenseApprovalService = expenseApprovalService;
        }
        public async Task<IActionResult> Index()
        {
            var expappList = await expenseApprovalService.GetAll();
            ViewBag.expappList = new SelectList((expappList).Select(s => new { Id = s.Id, RefNo = s.RefNo }), "Id", "RefNo");
            var data = await expenseApprovalService.GetAll();
            return View(data);
        }

        public async Task<IActionResult> ExpenseList()
        {
            var expappList = await expenseApprovalService.GetAll();
            ViewBag.expappList = new SelectList((expappList).Select(s => new { Id = s.Id, RefNo = s.RefNo }), "Id", "RefNo");
            var data = await expenseApprovalService.GetAll();
            return View(data);
        }
        public async Task<IActionResult> Create()
        {
            var expappList = await expenseApprovalService.GetAll();
            ViewBag.expappList = new SelectList((expappList).Select(s => new { Id = s.Id, RefNo = s.RefNo }), "Id", "RefNo");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ExpenseApprovalServiceVM model)
        {
            try
            {
                var result = await expenseApprovalService.AddNewExpenseApproval(model);
                return RedirectToAction("Index");
            }
            catch
            (Exception ex)
            {
                return View(model);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            var expappList = await expenseApprovalService.GetAll();
            ViewBag.expappList = new SelectList((expappList).Select(s => new { Id = s.Id, RefNo = s.RefNo }), "Id", "RefNo");
            var obj = await expenseApprovalService.GetById(id);
            return View(obj);
        }
        [HttpPost]
        public async Task<IActionResult>Edit(ExpenseApprovalServiceVM model)
        {
            try
            {
                var result = await expenseApprovalService.UpdateExpense(model);
                return RedirectToAction("Index");
            }
            catch
            (Exception ex)
            {
                return View(model);
            }
        }
        public async Task<IActionResult> Delete(long id)
        {
            var obj = await expenseApprovalService.Remove(id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Complete(long id)
        {
            var obj = await expenseApprovalService.CompleteExpense(id);
            return RedirectToAction("Index");
        }

    }
}

DFMS/FirmWebApp/Controllers/Cow/FeedCategoryController.cs
using Firm.Service.Services.FeedCategory_Services;
using Microsoft.AspNetCore.Mvc;

namespace FirmWebApp.Controllers.Cow
{
    public class FeedCategoryController : Controller
    {
        public readonly IFeedCategoryService categoryService;
        public FeedCategoryController(IFeedCategoryService categoryService)
        {
            this.categoryService = categoryService;
        }
        public async Task<IActionResult> Index()
        {
            var list = await categoryService.GetAllWithStock();
            return View(list);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(FeedCategoryServiceVM model)
        {
            try
            {
                var result = await categoryService.AddNewFeedCategory(model);

                if (!string.IsNullOrEmpty(result.ErrorMessage))
                {
                    ViewData["ErrorMessage"] = result.ErrorMessage;
                    return View(model);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while feed category.");
                return View(model);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            var obj = await categoryService.GetById(id);
            return View(obj);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(FeedCategoryServiceVM model)
        {
            try
            {
                var result = await categoryService.UpdateFeedCategory(model);

                if (!string.IsNullOrEmpty(result.ErrorMessage))
                {
                    ViewData["ErrorMessage"] = result.ErrorMessage;
                    return View(model);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while updating feed category.");
                return View(model);
            }
        }


        public async Task<IActionResult> Delete(long id)
        {
            var obj = await categoryService.Remove(id);

            return RedirectToAction("Index");
        }
    }
}

DFMS/FirmWebApp/Controllers/Cow/FeedConsumptionBulkController.cs
using Firm.Service.Services.FeedCategory_Services;
using Firm.Service.Services.FeedConsumptionBulk_Services;
using Firm.Service.Services.FeedEntry_Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace FirmWebApp.Controllers.Cow
{
    public class FeedConsumptionBulkController : Controller
    {
        public readonly IFeedCategoryService feedCategoryService;
        public readonly IFeedConsumptionBulkService  feedConsumptionBulkService;
        public FeedConsumptionBulkController(IFeedCategoryService feedCategoryService, IFeedConsumptionBulkService feedConsumptionBulkService)
        {
            this.feedCategoryService = feedCategoryService;
            this.feedConsumptionBulkService = feedConsumptionBulkService;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.feedCategoryList = new SelectList((await feedCategoryService.GetAll()).Select(s => new { Id = s.Id, Name = s.FeedCategoryName }), "Id", "Name");
            var data = await feedConsumptionBulkService.GetAll();
            return View(data);
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.feedCategoryList = new SelectList((await feedCategoryService.GetAll()).Select(s => new { Id = s.Id, Name = s.FeedCategoryName }), "Id", "Name");
            return View();
        } 
        
        
        public async Task<IActionResult> ShadeLineFeedList(FeedConsumptionBulkServiceVM model)
        {
            ViewBag.feedCategoryList = new SelectList((await feedCategoryService.GetAll()).Select(s => new { Id = s.Id, Name = s.FeedCategoryName }), "Id", "Name");

             model.feedConsumptionList = await feedConsumptionBulkService.ShadeLineFeedList();
            


            return View("Views/FeedConsumptionBulk/Create.cshtml",model);
        }


        [HttpPost]
        public async Task<IActionResult> Create(FeedConsumptionBulkServiceVM model)
        {
            try
            {
                var result = await feedConsumptionBulkService.AddNewFeedConsumptionBulk(model);

                if (!string.IsNullOrEmpty(result.ErrorMessage))
                {
                    ViewData["ErrorMessage"] = result.ErrorMessage;
                    ViewBag.feedCategoryList = new SelectList((await feedCategoryService.GetAll()).Select(s => new { Id = s.Id, Name = s.FeedCategoryName }), "Id", "Name");
                    return View(model);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while adding Feed Entry.");
                return View(model);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            ViewBag.feedCategoryList = new SelectList((await feedCategoryService.GetAll()).Select(s => new { Id = s.Id, Name = s.FeedCategoryName }), "Id", "Name");
            var obj = await feedConsumptionBulkService.GetById(id);
            return View(obj);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(FeedConsumptionBulkServiceVM model)
        {
            try
            {
                var result = await feedConsumptionBulkService.UpdateFeedConsumptionBulk(model);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while adding Feed Entry.");
                return View(model);
            }
        }


        public async Task<IActionResult> Delete(long id)
        {
            var obj = await feedConsumptionBulkService.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

DFMS/FirmWebApp/Views/Cow/Create.cshtml
@using static Firm.Utility.Miscellaneous.Enum
@model CowServiceViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}


<section class="content">
    <div class="container-fluid">
        <div class="">
            <div class="card-header">
                <h5 class="card-title">Cow Information (গরুর তথ্য)</h5>

            </div>

            <div class="card-body">
                <form asp-action="Create" asp-controller="Cow" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    @if (!string.IsNullOrEmpty(ViewData["ErrorMessage"] as string))
                    {
                        <div class="alert alert-warning">
                            @ViewData["ErrorMessage"]
                        </div>
                    }
                    <div class="row mx-2">


                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="PurchaseDate" class="control-label">Purchase Date (কেনার তারিখ)</label>
                                <input asp-for="PurchaseDate" class="form-control" placeholder="Enter purchase date">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="Origin" class="control-label"> Purchased From (কোথা থেকে কেনা) </label>
                                <input asp-for="Origin" class="form-control" id="origin" placeholder="Enter Source">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="Price" class="control-label">Purchase Price (ক্রয় মূল্য)</label>
                                <input asp-for="Price" class="form-control" id="price" placeholder="Enter price">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="BreedId" class="control-label">Breed (জাত)</label>
                                <select asp-for="BreedId" class="form-control"  asp-items="ViewBag.breedlist">
                                    <option value="">-- Select Breed --</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="Color" class="control-label"> Color (রঙ) </label>
                                <input asp-for="Color" class="form-control" id="cowcolor" placeholder="Enter Color">
                            </div>
                        </div>

                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="Weight" class="control-label">Weight (KG) /  ওজন (কেজি)</label>
                                <input asp-for="Weight" class="form-control" id="cow-weight" placeholder="Enter weight">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">

                            <div class="form-group">
                                <label asp-for="Age" class="control-label">Age (Months) / বয়স (মাস) </label>
                                <input asp-for="Age" class="form-control" placeholder="Enter age">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="CalfGender" class="control-label">Gender (লিঙ্গ)</label>
                                <select asp-for="CalfGender" asp-items="Html.GetEnumSelectList<Gender>()" class="form-control"></select>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="LivestockTypeVal" class="control-label"> Type (ধরণ)</label>
                                <select asp-for="LivestockTypeVal" asp-items="Html.GetEnumSelectList<LivestockType>()" class="form-control"></select>
                            </div>
                        </div>

                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="CowTeeth" class="control-label">Teeth (দাঁত)</label>
                                <input asp-for="CowTeeth" class="form-control" id="cow-weight" placeholder="No of Teeth">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="ShedNo" class="control-label">Shed No. (চালার নম্বর)</label>
                                <input asp-for="ShedNo" class="form-control" id="cow-weight" placeholder="No of Shed">
                            </div>
                        </div>
                        
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="LineNo" class="control-label">Line No. (সারি নম্বর)</label>
                                <input asp-for="LineNo" class="form-control" id="cow-weight" placeholder="No of Line">
                            </div>
                        </div>

                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="TagId" class="control-label">Tag No.(ট্যাগ)</label>
                                <input asp-for="TagId" class="form-control" placeholder="Enter Tag">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-lg-6">
                            <div class="form-group">
                                <label asp-for="MotherTag" class="control-label">Mother Tag (মায়ের ট্যাগ)</label>
                                <input asp-for="MotherTag" class="form-control" id="calf-age" placeholder="Enter Mother Tag">
                            </div>
                        </div>

                    </div>
                    <div class="row mx-2 ">
                        <div class="form-group col-sm-12 ">
                            <a asp-action="Index" asp-controller="Cow" class="btn btn-light mr-2">
                                Cancel
                            </a>
                            <button type="submit" class="btn btn-primary float-End">Submit</button>
                        </div>
                    </div>


                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            $('#Configuration').addClass('menu-open');
            $('#Cow').addClass('active');

        });
    </script>
    <script>
        window.setTimeout(function () {
            $(".alert").fadeTo(500,).slideUp(500, function () {
                $(this).remove();
            });
        }, 4000);
    </script>
  }